[package]
name = "qmrl"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.5"
rand = "0.8.5"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"

