#!/bin/bash
path=$2
file=${path##*/}  
base=${file%.qmrl}

if [ "$1" == "compile" ]; then
    QMRL_PATH=$path cargo build --release --bin run-custom

    cp target/release/run-custom solvers/${base}
elif [ "$1" == "run" ];
     then

        # run the program
        solvers/${base} $3 $4 $5 | python -m json.tool 
    else
        echo "Invalid argument. Please use 'run' or 'compile'"
fi