[package]
name = "solver"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
petgraph = "0.7.1"
rand = "0.9.0"
regex = "1.11.1"
rustworkx-core = "0.16.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
vf2 = {path = "../../vf2"}
